# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31db246750542d9abf22052510f1a739f72e3cdd2161a8fc8fc718949b6b2f0ec2bc08c2c4b444843f260d0714d1854fdac56d93734028653ef04fe917246016

test:
  secret_key_base: eb2ff705a9407cc22301614aa486f405461842be91e57087c2de8a3fd6e0cb502c262327d8b877a23d3135ae2f016197cb337d84e78c8153c9c2f31953911088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
